dev-guide/general-api/authentication.rst, dev-guide/preface.rst
found a few last minute discrepancies which I fixed for inter-doc consistency.
=> last fixes for authentication and external links

dev-guide/overview/index.rst
=> changed software to service

dev-guide/api-operations/svr-basic-operations.rst, dev-guide/extensions/index.rst, dev-guide/extensions/rackspace-extensions.rst
I jumped the gun, publishing this information, so retracting it now.
=> Remove sched hint documentation.

dev-guide/api-operations/svr-basic-operations.rst, dev-guide/api-reference.rst, dev-guide/developer-guide.rst, dev-guide/index.rst, dev-guide/release-notes.rst
This adds support for https://github.com/rackerlabs/nexus-control/pull/248.
=> make tweaks necessary to add collapsible sections

pom.xml
=> Corrected update to rackspace-docs-parent-1.0.1-SNAPSHOT

README.md, api-docs/README.md
(bad branch name, but correct content)
=> Apply new README template to Guide  

README.md, api-docs/README.md
=> Readme fix typo

api-docs/api-operations/methods/post-create-network-os-networksv2.rst, api-docs/conf.py, api-docs/general-api-info/role-based-access-control.rst, api-docs/general-api-info/service-access-endpoints.rst, api-docs/getting-started.rst, api-docs/getting-started/create-network/create-network.rst, api-docs/overview/additional-resources.rst, api-docs/overview/index.rst
Replace kc extlink refs with how-to:
=> Update extlink library

api-docs/common-gs/auth-using-nova.rst, api-docs/common-gs/using-client.rst
including the os-auth-system variable and mention that the password is the API key.
=> Updated authentication for nova

api-docs/api-operations/methods/post-lock-specified-server-servers-server-id-actions.rst, api-docs/api-operations/methods/post-start-specified-server-servers-server-id-actions.rst, api-docs/api-operations/methods/post-stop-specified-server-servers-server-id-actions.rst, api-docs/api-operations/methods/post-unlock-specified-server-servers-server-id-actions.rst, api-docs/api-operations/svr-basic-operations.rst
Closes issue# 154
Doc team: Use the quality checklist at http://goo.gl/forms/GaRzOmhzr5 to ensure that the 
content of the PR meets minimal writing and style requirements, and has received an 
appropriate subject matter expert (SME) review. Complete the checklist for significant
doc changes or additions that you submit or that are submitted by a non-doc staff contributor.
=> Ccl issue 154

api-docs/api-operations/methods/post-stop-specified-server-servers-server-id-actions.rst
=> added billing implication to stop operation.

api-docs/common-gs/how-to-use-curl.rst
Doc team: Use the quality checklist at http://goo.gl/forms/GaRzOmhzr5 to ensure that the 
content of the PR meets minimal writing and style requirements, and has received an 
appropriate subject matter expert (SME) review. Complete the checklist for significant
doc changes or additions that you submit or that are submitted by a non-doc staff contributor.
Closes issue #165
=> update auth content in cURL section

api-docs/api-reference/methods/post-create-server-with-sched-hint-servers.rst, api-docs/api-reference/svr-basic-operations.rst, api-docs/extensions/index.rst, api-docs/extensions/rackspace-extensions.rst, api-docs/release-notes/index.rst, api-docs/release-notes/releases/cs-v2-20160815.rst
=> publish scheduler hints in aid of shared IP rollout in networks docs

api-docs/additional-resources.rst, api-docs/api-reference/methods/get-list-servers-server-id-os-volume-attachments.rst, api-docs/api-reference/methods/post-attach-volume-to-server-servers-server-id-os-volume-attachments.rst, api-docs/api-reference/methods/post-set-image-metadata-for-specified-image-images-image-id-metadata.rst, api-docs/common-gs/auth-using-curl.rst, api-docs/common-gs/using-client.rst, api-docs/general-api-info/role-based-access-control.rst, api-docs/getting-started/authenticate.rst, api-docs/getting-started/create-network-intro.rst, api-docs/getting-started/index.rst, api-docs/getting-started/send-request-ovw.rst, api-docs/release-notes/releases/cs-v2-20120709.rst, api-docs/release-notes/releases/cs-v2-20120815.rst
Enhancements to fix issue #181 #180 #177 #175
=> Fix issues 181 180 177 175

api-docs/api-reference/methods/post-create-bootable-volume-and-server-servers.rst, api-docs/extensions/ext-boot-from-volume.rst
=> closes issue #182

api-docs/api-reference/methods/post-create-server-with-sched-hint-servers.rst
=> Correct the parameter nesting per H2 issue #2137

api-docs/getting-started/create-server/listing-images-curl.rst
=> Correct link for listing images

api-docs/api-reference/methods/post-create-bootable-volume-and-server-servers.rst
=> Correct parameter optional /required indications

api-docs/api-reference/methods/post-create-bootable-volume-and-server-servers.rst, api-docs/api-reference/methods/post-create-server-servers.rst, api-docs/api-reference/methods/post-create-server-with-disk-config-servers.rst, api-docs/api-reference/methods/post-create-server-with-network-servers.rst, api-docs/api-reference/methods/post-create-server-with-sched-hint-servers.rst
=> just fixing a typo

api-docs/api-reference/methods/delete-delete-volume-attachment-from-server-servers-server-id-os-volume-attachments-attachment-id.rst
=> corrected parameter name

api-docs/api-reference/methods/post-get-console-servers-server-id-action.rst
=> fix get console per issue #197

api-docs/conf.py
=> Update CPP links

api-docs/additional-resources.rst
it wasn't actually used...but got rid of it anyway!
=> remove ref to community

api-docs/common-gs/how-to-use-curl.rst, api-docs/common-gs/using-client.rst, api-docs/general-api-info/role-based-access-control.rst, api-docs/general-api-info/service-access.rst, api-docs/getting-started/authenticate.rst, api-docs/index.rst, api-docs/release-notes/releases/cs-v2-20120501.rst, api-docs/release-notes/releases/cs-v2-20120709.rst, api-docs/release-notes/releases/cs-v2-20120815.rst
requested by the Identity dev team
=> Change all occurrences of Rackspace Identity to Identity as

api-docs/additional-resources.rst, api-docs/api-reference/index.rst, api-docs/index.rst
=> de-emphasize sdks and rack cli

api-docs/getting-started/create-server/booting-server-curl.rst, api-docs/getting-started/create-server/booting-server-nova.rst
=> add config-drive parameter to boot calls

api-docs/api-reference/methods/post-reset-network-for-specified-server-servers-server-id-actions.rst, api-docs/api-reference/svr-basic-operations.rst
=> add reset network operation

api-docs/common-gs/using-client.rst, api-docs/extensions/ext-config-drive.rst, api-docs/getting-started/create-server/listing-servers-curl.rst
=> Change Ubuntu to the Ubuntu operating system

api-docs/api-reference/methods/post-migrate-server-server-id-actions.rst, api-docs/api-reference/svr-basic-operations.rst
New API call "migrate" added to docs
=> added server migration action

api-docs/api-reference/methods/post-create-bootable-volume-and-server-servers.rst
=> SourceType specification per Joe.

api-docs/getting-started/create-server/listing-images-nova.rst
JIRA 6568
The list of available images was extremely out of date, so this PR updates the list to reflect the currently available images.
=> update list of images
